version: '3'

services: 
  # dev:
  #   container_name: go
  #   tty: true
  #   build: ./
  #   volumes: 
  #     - ./:/go/src
  prod:
    container_name: go
    image: josecjr/codeeducation
    tty: true
    build: 
        context: .
        dockerfile: Dockerfile.Prod